price<-hpriceme$price
assess<-hpriceme$assess
sqrft<-hpriceme$sqrft
lotsize<-hpriceme$lotsize
bdrms<-hpriceme$bdrms
library(stats)
library(quantmod)
library(car)
priceassess<-lm(price~assess)
summary(priceassess)
assess10k<-assess+10000
priceassess10k<-lm(price~assess10k)
summary(priceassess10k)
sum(priceassess$residuals)
sum(priceassess10k$residuals)
pred300k<-priceassess$coefficients[1]+priceassess$coefficients[2]*300000
linearHypothesis(priceassess,c("(Intercept)=0"))
linearHypothesis(priceassess,c("assess=1"))
linearHypothesis(priceassess,c("assess=1","(Intercept)=0"))
