Caseshillerhomeprice<-read.csv("CSUSHPISA.csv") #S&P/Case-Shiller U.S. National Home Price Index
Crudeoil<-read.csv("MCOILWTICO.csv") #Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma
loansleasesoutstanding<-read.csv("DTTHFM.csv") #Total Loans and Leases Outstanding at Domestic Finance Companies, Outstanding
homepriceindex<-ts(Caseshillerhomeprice[,2],frequency = 12,start=c(1987,1))
wti<-ts(Crudeoil[,2],frequency = 12,start=c(1987,1))
loansleases<-ts(loansleasesoutstanding[,2],frequency = 12,start=c(1987,1))
indexonwti<-dynlm(homepriceindex~wti)
indexonloans<-dynlm(homepriceindex~wti)
wtinonloan<-dynlm(wti~loansleases)
allthree<-dynlm(homepriceindex~wti+loansleases)
summary(indexonwti)
summary(indexonloans)
summary(wtinonloan)
summary(allthree)
summary(homepriceindex)
sd(homepriceindex)
summary(wti)
sd(wti)
summary(loansleases)
sd(loansleases)
intord(homepriceindex)
intord(wti)
intord(loansleases)
allthree1<-dynlm(diff(homepriceindex)~diff(wti)+diff(loansleases))
summary(allthree1)
