df= read.csv("historicstats.csv")
dfts=ts(df[,2:7],frequency = 1,start = c(1892,1))
yl= log(dfts[,1])
w= log(dfts[,2])
un=log(dfts[,3])
tud=log(dfts[,4])
L=log(dfts[,5])
kl=log(dfts[,6])
library(tseries)
library(urca)
source(file="intord.R")
#for yl
yln=ur.df(yl,type="none",selectlags = "BIC")
summary(yln)
yld=ur.df(yl,type="drift",selectlags = "BIC")
summary(yld)
ylt=ur.df(yl,type="trend",selectlags = "BIC")
summary(ylt)
#for w
wn=ur.df(w,type="none",selectlags = "BIC")
summary(wn)
wd=ur.df(w,type="drift",selectlags = "BIC")
summary(wd)
wt=ur.df(w,type="trend",selectlags = "BIC")
summary(wt)
#1st diff
w1n=ur.df(diff(w),type="none",selectlags = "BIC")
summary(w1n)
w1d=ur.df(diff(w),type="drift",selectlags = "BIC")
summary(w1d)
w1t=ur.df(diff(w),type="trend",selectlags = "BIC")
summary(w1t)
#for un
unn=ur.df(un,type="none",selectlags = "BIC")
summary(unn)
und=ur.df(un,type="drift",selectlags = "BIC")
summary(und)
unt=ur.df(un,type="trend",selectlags = "BIC")
summary(unt)
#1st difference
un1n=ur.df(diff(un),type="none",selectlags = "BIC")
summary(un1n)
un1d=ur.df(diff(un),type="drift",selectlags = "BIC")
summary(un1d)
un1t=ur.df(diff(un),type="trend",selectlags = "BIC")
summary(un1t)
#for tud
tudn=ur.df(tud,type="none",selectlags = "BIC")
summary(tudn)
tudd=ur.df(tud,type="drift",selectlags = "BIC")
summary(tudd)
tudt=ur.df(tud,type="trend",selectlags = "BIC")
summary(tudt)
#1st difference
tud1n=ur.df(diff(tud),type="none",selectlags = "BIC")
summary(tud1n)
tud1d=ur.df(diff(tud),type="drift",selectlags = "BIC")
summary(tud1d)
tud1t=ur.df(diff(tud),type="trend",selectlags = "BIC")
summary(tud1t)
#for lm
Ln=ur.df(L,type="none",selectlags = "BIC")
summary(Ln)
Ld=ur.df(L,type="drift",selectlags = "BIC")
summary(Ld)
Lt=ur.df(L,type="trend",selectlags = "BIC")
summary(Lt)
#1st diff
L1n=ur.df(diff(L),type="none",selectlags = "BIC")
summary(L1n)
L1d=ur.df(diff(L),type="drift",selectlags = "BIC")
summary(L1d)
L1t=ur.df(diff(L),type="trend",selectlags = "BIC")
summary(L1t)
#for kl
kln=ur.df(kl,type="none",selectlags = "BIC")
summary(kln)
kld=ur.df(kl,type="drift",selectlags = "BIC")
summary(kld)
klt=ur.df(kl,type="trend",selectlags = "BIC")
summary(klt)
#1st difference
kl1n=ur.df(diff(kl),type="none",selectlags = "BIC")
summary(kl1n)
kl1d=ur.df(diff(kl),type="drift",selectlags = "BIC")
summary(kl1d)
kl1t=ur.df(diff(kl),type="trend",selectlags = "BIC")
summary(kl1t)
#just to check
intord(yl)
intord(w)
intord(un)
intord(tud)
intord(L)
intord(kl)

