dt = read.csv("historicstats.csv", header = TRUE)
str(dt)
View(dt)
dts <- ts(dt, start = 1892, end = 1997)
plot.ts(dts)
lyl <- log(dts[,2])
plot.ts(dts[,2])
plot.ts(lyl)
lw <- log(dts[,3])
plot.ts(lw)
lun <- log(dts[,4])
plot.ts(lun)
ltud <- log(dts[,5])
plot.ts(ltud)
ll <- log(dts[,6])
plot.ts(ll)
lkl <- log(dts[,7])
plot.ts(lkl)
source(file="intord.R")
intord(lyl)
library(urca)
dlyl = ur.df(lyl, type = "none", selectlags = "BIC")
summary(dlyl)
ddflyl = ur.df(lyl, type = "drift", selectlags = "BIC")
summary(ddflyl)
dflyl = ur.df(lyl, type = "trend", selectlags = "BIC")
summary(dflyl)
intord(lw)
dlw = ur.df(lw, type = "none", selectlags = "BIC")
summary(dlw)
ddlw = ur.df(lw, type = "drift", selectlags = "BIC")
summary(ddlw)
dddlw = ur.df(lw, type = "trend", selectlags = "BIC")
summary(dddlw)
dlw=diff(lw)
ddddlw = ur.df(dlw, type = "trend", selectlags = "BIC")
summary(ddddlw)
intord(lun)
dlun =ur.df(lun, type = "none", selectlags = "BIC")
summary(dlun)
ddlun = ur.df(lun, type = "drift", selectlags = "BIC")
summary(ddlun)
dddlun = ur.df(lun, type = "trend", selectlags = "BIC")
summary(dddlun)
dlun = diff(lun)
ddddlun = ur.df(dlun, type = "trend", selectlags = "BIC")
summary(ddddlun)
intord(ltud)
dltud = ur.df(ltud, type = "none", selectlags = "BIC")
summary(dltud)
ddltud = ur.df(ltud, type = "drift", selectlags = "BIC")
summary(ddltud)
dddltud = ur.df(ltud, type = "trend", selectlags = "BIC")
summary(dddltud)
dltud = diff(ltud)
ddddltud = ur.df(dltud, type = "trend", selectlags = "BIC")
summary(ddddltud)
intord(dltud)
intord(ll)
dll = ur.df(ll, type = "none", selectlags = "BIC")
summary(dll)
ddll = ur.df(ll, type = "drift", selectlags = "BIC")
summary(ddll)
dddll = ur.df(ll, type = "trend", selectlags = "BIC")
summary(dddll)
lld = diff(ll)
dddlld = ur.df(lld, type = "trend", selectlags = "BIC")
summary(dddlld)
intord(lkl)
dlkl = ur.df(lkl, type = "none", selectlags = "BIC")
summary(dlkl)
ddlkl = ur.df(lkl, type = "drift", selectlags = "BIC")
summary(ddlkl)
dddlkl = ur.df(lkl, type = "trend", selectlags = "BIC")
summary(dddlkl)
lkld = diff(lkl)
dddlkld = ur.df(lkld, type = "trend", selectlags = "BIC")
summary(dddlkld)

ffr = read.csv("ffrate.csv", header = TRUE)
View(ffr)
str(ffr)
ffrts = ts(ffr, frequency = 12, start = c(1982, 11), end =  c(2000, 12) )
frate = ffrts[,1]
inf = ffrts[,3]
plot.ts(frate)
plot.ts(dfrate)
plot.ts(infd)
plot.ts(inf)
intord(frate)
intord(inf)
plot.ts(inf)
infd = diff(inf)
intord(infd)
dinf = ur.df(inf, type = "trend", selectlags = "BIC")
summary(dinf)
dfrate = diff(frate)


reg1=dynlm(dfrate~L(dfrate,1:24)+L(inf,0:24))
summary(reg1)
AIC(reg1)
BIC(reg1)
reg2 = dynlm(dfrate~L(dfrate,1:23)+L(inf,0:24))
summary(reg2)
AIC(reg2)
BIC(reg2)
stargazer(reg2, type = "text")
reg3 = dynlm(dfrate~L(dfrate,1:24)+L(infd,0:19))
summary(reg3)
AIC(reg3)
BIC(reg3)
reg4 = dynlm(dfrate~L(dfrate,1:23)+L(infd,0:19))
summary(reg4)
AIC(reg4)
BIC(reg4)
reg5 = dynlm(dfrate~L(dfrate,1:14)+L(infd,0:19))
summary(reg5)
AIC(reg4)
BIC(reg4)
reg6=dynlm(dfrate~L(dfrate,1:14)+L(inf,0:24))
summary(reg6)
AIC(reg6)
BIC(reg6)
reg7=dynlm(dfrate~L(dfrate,1:1)+L(inf,0:12))
summary(reg7)
AIC(reg7)
BIC(reg7)

order <- 1:24

BICs <- sapply(order, function(x) 
  "AR" = BIC(dynlm(dfrate~L(dfrate,1:x)+ L(infd,0:x))))

BICs

bgtest(reg1, order = 1)
bgtest(reg1, order = 2)
bgtest(reg1, order = 3)
bgtest(reg1, order = 4)
bgtest(reg1, order = 5)
bgtest(reg1, order = 6)

stargazer(reg2, type="text", dep.var.labels.include=FALSE)

library("dynlm")
library("forecast")
library("tseries")
library("quantmod")
library("stats")

sea = seasonaldummy(dfrate)
r1 = dynlm(dfrate~sea)
summary(r1)

stargazer(r1, type = "text", dep.var.labels.include = FALSE)

see = seasonaldummy(frate)
r2 = dynlm(frate~see)
summary(r2)

scea = seasonaldummy(inf)
r3 = dynlm(inf~scea)
summary(r3)
