---
title: "project2"
output: html_document
  word_document: default
  html_document: default
---
```{r warning=FALSE, error=FALSE}
library("dynlm")
library("forecast")
library("tseries")
library("quantmod")
library("stats")
library("urca")
library(lmtest)
```

```{r}
source(file="intord.R")
df1<-read.csv("wage and salary.csv")
df2<-read.csv("consumer loans.csv")
df3<-read.csv("PCE.csv")
wage<-ts(df1[,2],frequency = 12,start = c(2000,07))
loans<-ts(df2[,2],frequency = 12,start = c(2000,07))
PCE<-ts(df3[,2],frequency = 12,start = c(2000,07))
#stationarity
waget=ur.df(wage,type="trend",selectlags = "BIC")
summary(waget) 
intord(wage)
wage1<-diff(wage)
wage1t=ur.df(wage1,type="trend",selectlags = "BIC")
summary(wage1t) 
loanst<-ur.df(loans,type="trend",selectlags = "BIC")
summary(loanst)
intord(loans)
loans1<-diff(loans)
loans1t<-ur.df(loans1,type="trend",selectlags = "BIC")
summary(loans1t)
PCEt<-ur.df(PCE,type="trend",selectlags = "BIC")
summary(PCEt)
intord(PCE)
PCE1<-diff(PCE)
PCE1t<-ur.df(PCE1,type="trend",selectlags = "BIC")
summary(PCE1t)
#first difference for everyone
#dynamic regression
Reg1<-dynlm(loans1~L(loans1,1:24)+L(wage1,0:24)+L(PCE1,0:24))
summary(Reg1)
#0 #18 #18 #2002,8
Reg2<-dynlm(loans1~L(wage1,0:18)+L(PCE1,0:18),start = c(2002,8))
summary(Reg2)

AIC(Reg1)
BIC(Reg1)
AIC(Reg2)
BIC(Reg2)
#seasonality
seawage<-seasonaldummy(wage1)
s1<-dynlm(wage1~seawage)
sealoans<-seasonaldummy(loans1)
s2<-dynlm(loans1~sealoans)
seapce<-seasonaldummy(PCE1)
s3<-dynlm(PCE1~seapce)
summary(s1)
summary(s2)
summary(s3)
Regx<-dynlm(loans1~L(wage1,0:18)+L(PCE1,0:18)+sealoans,start = c(2002,8))
summary(Regx)
anova(Regx,Reg2,test="F") #cannot reject the null dummy avoid

bgtest(Reg2,order=1) 
bgtest(Reg2,order=2) 
bgtest(Reg2,order=3) 
bgtest(Reg2,order=4) 
bgtest(Reg2,order=5) 
bgtest(Reg2,order=6)
RegY<-dynlm(loans1~L(wage1,0:22)+L(PCE1,0:20),start = c(2002,8))
summary(RegY)
AIC(RegY)
BIC(RegY)
AIC(Reg2)
BIC(Reg2)
bgtest(RegY,order=1) 
bgtest(RegY,order=2) 
bgtest(RegY,order=3) 
bgtest(RegY,order=4) 
bgtest(RegY,order=5) 
bgtest(RegY,order=6)
Reg11<-dynlm(loans1~L(wage1,0:22),start = c(2002,8))
anova(Reg11,RegY,test="F")
Reg12<-dynlm(loans1~L(PCE1,0:20),start = c(2002,8))
anova(Reg12,RegY,test="F")

```

